services:
    collectionRoute:
        class:     Opine\Collection\Route
        arguments: [@route, @collectionModel]
    collection:
        class:     Opine\Collection\Service
        arguments:
            - %root%
            - @collectionModel
            - @route
            - @db
            - @language
            - @person
            - @search
    collectionModel:
        class:     Opine\Collection\Model
        arguments: [%root%, @db, @bundleModel]
    collectionController:
        class:     Opine\Collection\Controller
        arguments: [@collectionModel, @collectionView, @collection, @person, @language]
    collectionView:
        class:     Opine\Collection\View
        arguments: [@layout]
